# version: '3.8'

# services:
#   # rabbitmq:
#   #   image: rabbitmq:3-management
#   #   deploy:
#   #     restart_policy:
#   #         condition: on-failure
#   #   ports:
#   #     - "5672:5672"         # AMQP
#   #     - "15672:15672"       # Management UI
#   #   environment:
#   #     RABBITMQ_DEFAULT_USER: guest
#   #     RABBITMQ_DEFAULT_PASS: guest

#   inventory-service:
#     build: ./inventory-service
#     # depends_on:
#     #   - inventory-db
#     #   - rabbitmq
#     environment:
#       DB_HOST: inventory-db
#       DB_USER: postgres
#       DB_PASS: postgres
#       DB_NAME: inventory
#       RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
#     ports:
#       - "3001:3000"

# #   inventory-db:
# #     image: postgres:14
# #     environment:
# #       POSTGRES_DB: inventory
# #       POSTGRES_USER: postgres
# #       POSTGRES_PASSWORD: postgres
# #     volumes:
# #       - inventory-data:/var/lib/postgresql/data

# #   harvest-service:
# #     build: ./harvest-service
# #     depends_on:
# #       - harvest-db
# #       - rabbitmq
# #     environment:
# #       DB_HOST: harvest-db
# #       DB_USER: postgres
# #       DB_PASS: postgres
# #       DB_NAME: harvest
# #       RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
# #     ports:
# #       - "3002:3000"

# #   harvest-db:
# #     image: postgres:14
# #     environment:
# #       POSTGRES_DB: harvest
# #       POSTGRES_USER: postgres
# #       POSTGRES_PASSWORD: postgres
# #     volumes:
# #       - harvest-data:/var/lib/postgresql/data

# #   shipping-service:
# #     build: ./shipping-service
# #     depends_on:
# #       - shipping-db
# #       - rabbitmq
# #     environment:
# #       DB_HOST: shipping-db
# #       DB_USER: postgres
# #       DB_PASS: postgres
# #       DB_NAME: shipping
# #       RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
# #     ports:
# #       - "3003:3000"

# #   shipping-db:
# #     image: postgres:14
# #     environment:
# #       POSTGRES_DB: shipping
# #       POSTGRES_USER: postgres
# #       POSTGRES_PASSWORD: postgres
# #     volumes:
# #       - shipping-data:/var/lib/postgresql/data

# # volumes:
# #   inventory-data:
# #   harvest-data:
# #   shipping-data:
